# Oct 19

In [5]:
#Multidimentional arrays with coordinates
import numpy as np
data=np.array([1,2,3])
print(data[:2], 'up to 2nd') #useful for header
print(data[-2:], 'all following 2nd last')
print(data[::-1], 'reverse') #all before the -1

#With matrix, [:all row, 3column]

[1 2] up to 2nd
[2 3] all following 2nd last
[3 2 1] reverse


In [10]:
# 2x3 x 3x1 operable
nrows, ncols= 10, 20
z= np.zeros((nrows, ncols))
print(z)
print(z.shape)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(10, 20)


In [14]:
new=np.arange(0,10,2)
t_axis= np.arange(0,60,10)
print(new)
x_axis=np.linspace(0,60,6)
print(x_axis) #not integer
x2=np.linspace(0,60,19)
#print('{0:.2f}'.format(j) for j in x2) can't format an array

x2r=np.round(x2, 2)
print(x2r) 

[0 2 4 6 8]
[ 0. 12. 24. 36. 48. 60.]
[ 0.    3.33  6.67 10.   13.33 16.67 20.   23.33 26.67 30.   33.33 36.67
 40.   43.33 46.67 50.   53.33 56.67 60.  ]


In [19]:
a=np.array([1,2])
b=a*1.5
print(b)
#we use array because operations are already considered

[1.5 3. ]


# Oct 18
Read from file, recovered

In [1]:
myfl = open('1018.txt','wt')
myfl.write('questa è una stringa\n')
myfl.write('sulla riga seguente c\'è un numero\n')
myfl.write(str(10)+'\n')
myfl.close()

In [2]:
rows=[]
for i in range(1,11):
    rows.append('stringa {0}\n'.format(i)) #try with and without \n
#overwriting on file
myfl = open('1018.txt','at')
myfl.writelines(rows)
myfl.close()

In [3]:
myfl = open('1018.txt','a') # t not necessary
nc = myfl.write('\n another character string with a non-ascii character: è\n')
print('I wrote {0} more characters in the file'.format(nc))

I wrote 57 more characters in the file


In [5]:
 # opening the file in reading mode
myfl = open('1018.txt')# (default 'rt')
# reading the file in one line
mystr=myfl.read()
# close teh file
myfl.close()
# print the line
print(mystr)
mystr


questa è una stringa
sulla riga seguente c'è un numero
10
stringa 1
stringa 2
stringa 3
stringa 4
stringa 5
stringa 6
stringa 7
stringa 8
stringa 9
stringa 10



"questa è una stringa\nsulla riga seguente c'è un numero\n10\nstringa 1\nstringa 2\nstringa 3\nstringa 4\nstringa 5\nstringa 6\nstringa 7\nstringa 8\nstringa 9\nstringa 10\n"

In [6]:
myfl = open('1018.txt')
# rading a list of strings
rows=myfl.readlines()
# closing the file
myfl.close()
#printing the strings of the list
for row in rows:
    print(row, end="")
"""
two \n: one in line, one added byprint,
use row.strip() to delete the first one
or the end parameter of print to eliminate the second one
"""

questa è una stringa
sulla riga seguente c'è un numero
10
stringa 1
stringa 2
stringa 3
stringa 4
stringa 5
stringa 6
stringa 7
stringa 8
stringa 9
stringa 10

 another character string with a non-ascii character: è


'\ntwo \n: one in line, one added byprint,\nuse row.strip() to delete the first one\nor the end parameter of print to eliminate the second one\n'

In [16]:
myfl = open('1018.txt')
row = "segnaposto"
while row:
    row=myfl.readline()
    print(row,end='')
myfl.close()

questa è una stringa
sulla riga seguente c'è un numero
10
stringa 1
stringa 2
stringa 3
stringa 4
stringa 5
stringa 6
stringa 7
stringa 8
stringa 9
stringa 10

 another character string with a non-ascii character: è


In [18]:
with open('1018.txt') as f:
    rows = f.readlines()
# the file is closed
# I use the strings stored in the rows list
for i,row in enumerate(rows):
    print(row.rstrip()*i)


sulla riga seguente c'è un numero
1010
stringa 1stringa 1stringa 1
stringa 2stringa 2stringa 2stringa 2
stringa 3stringa 3stringa 3stringa 3stringa 3
stringa 4stringa 4stringa 4stringa 4stringa 4stringa 4
stringa 5stringa 5stringa 5stringa 5stringa 5stringa 5stringa 5
stringa 6stringa 6stringa 6stringa 6stringa 6stringa 6stringa 6stringa 6
stringa 7stringa 7stringa 7stringa 7stringa 7stringa 7stringa 7stringa 7stringa 7
stringa 8stringa 8stringa 8stringa 8stringa 8stringa 8stringa 8stringa 8stringa 8stringa 8
stringa 9stringa 9stringa 9stringa 9stringa 9stringa 9stringa 9stringa 9stringa 9stringa 9stringa 9
stringa 10stringa 10stringa 10stringa 10stringa 10stringa 10stringa 10stringa 10stringa 10stringa 10stringa 10stringa 10

 another character string with a non-ascii character: è another character string with a non-ascii character: è another character string with a non-ascii character: è another character string with a non-ascii character: è another character string with a non-ascii

In [29]:
#***EXCEL***
import time as time
start_time = time.time()
ncols = 10
nrows = 10
#....
# Create the header
# header = ['intestazione-{0:02d}'.format(i) for i in range (1,ncols+1)]
header = [f'Header-{i:02d}' for i in range(1, ncols + 1)]
rows =[ [str(icol*10**(irow)) for icol in range(ncols)] for irow in range(nrows)]
# Write the data to a CSV file
with open('1018_test_csv.csv','wt') as fl:
    fl.write(','.join(header)+'\n')
    for columns in rows:
        fl.write(','.join(columns)+'\n')
end_time = time.time()
print('il codice ha impiegato ', end_time-start_time, 'seconds')

il codice ha impiegato  0.15900015830993652 seconds


In [ ]:
#version -2
start_time = time.time()
#I write one line at a time generating the data at the same time
with open('2_test_csv.csv','wt') as fl:
    for j in range(ncols):
            fl.write('Header-{0:02d},'.format(j+1))
        fl.write('\n')
    for i in range(nrows):
        for j in range(ncols):
            fl.write(str(j*(10**i))+',')
        fl.write('\n')
end_time = time.time()
print('il codice ha impiegato ', end_time-start_time, 'seconds')


In [2]:
#READ
# I load the data written into the file all in one go
with open('1018_test_csv.csv','rt') as fl:
    rows=fl.readlines()
header = [i.rstrip() for i in rows[0].split(',')]
dati = []
for row in rows[1:]:
    datiriga = [ int(i) for i in row.split(',')]
    dati.append(datiriga)
# testing the reading 1
print(header)
for r in dati:
    print(r)

['Header-01', 'Header-02', 'Header-03', 'Header-04', 'Header-05', 'Header-06', 'Header-07', 'Header-08', 'Header-09', 'Header-10']
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]
[0, 100, 200, 300, 400, 500, 600, 700, 800, 900]
[0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000]
[0, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 80000, 90000]
[0, 100000, 200000, 300000, 400000, 500000, 600000, 700000, 800000, 900000]
[0, 1000000, 2000000, 3000000, 4000000, 5000000, 6000000, 7000000, 8000000, 9000000]
[0, 10000000, 20000000, 30000000, 40000000, 50000000, 60000000, 70000000, 80000000, 90000000]
[0, 100000000, 200000000, 300000000, 400000000, 500000000, 600000000, 700000000, 800000000, 900000000]
[0, 1000000000, 2000000000, 3000000000, 4000000000, 5000000000, 6000000000, 7000000000, 8000000000, 9000000000]
